import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Image from "next/image";
import {menuItems} from '@/menuItem';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cyrus MicroCredit",
  description: "Generated by create next app",
  icons: {
    icon: '/Cyrus logo.png',
    shortcut: '/Cyrus logo.png',
    apple: '/Cyrus logo.png',
    other: {
      rel: 'icon',
      url: '/favicon.ico',
    },
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar
        logo={<span className="text-blue-800 font-bold">
          <Image src='/Cyrus logo.png' alt='logo' width={100} height={40}/>
        </span>}
        menuItems={menuItems}
      />
        {children}
        <Footer />
      </body>
    </html>
  );
}
