import type { Metadata } from "next";
import { Montserrat } from "next/font/google"; // Changed from Geist to Montserrat
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Image from "next/image";
import { menuItems } from '@/menuItem';

// Set up Montserrat font
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  // You can specify weights if needed (defaults to 400)
  // weight: ['400', '500', '700'],
});

export const metadata: Metadata = {
  title: "Cyrus MicroCredit",
  description: "Generated by create next app",
  icons: {
    icon: '/Cyrus logo.png',
    shortcut: '/Cyrus logo.png',
    apple: '/Cyrus logo.png',
    other: {
      rel: 'icon',
      url: '/favicon.ico',
    },
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased`} // Changed to use Montserrat directly
      >
        <Navbar
          logo={<span className="text-blue-800 font-bold">
            <Image src='/Cyrus logo.png' alt='logo' width={100} height={40} />
          </span>}
          menuItems={menuItems}
        />
        {children}
        <Footer />
      </body>
    </html>
  );
}